version: '3'

services:
  webserver:
    build: ./docker/webserver
    image: local-web-server
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./www:/var/www/html
    links:
      - database

  database:
    image: mysql:5.7
    ports:
      - "3316:3306"
    volumes:
      - ./db:/var/lib/mysql
      - ./docker/db:/docker-entrypoint-initdb.d/
    environment:
      - MYSQL_ROOT_PASSWORD= docker
      - MYSQL_USER= dbuser
      - MYAQL_PASSWORD= password
      - MYSQL_ROOT_HOST= %

